### ISSUE TITLE
Recommend Purgecss instead?

### ISSUE THREAD

**Issue by chmac** [rongierlach/gatsby-plugin-purify-css#11]
There is a [Gatsby plugin for purgecss](https://www.gatsbyjs.org/packages/gatsby-plugin-purgecss/) which works out of the box. Would it make sense to recommend that plugin instead of this one? As far as I can see it achieves a similar goal, has some download traction, and appears to work out of the box.

**Comment by youfoundron** [comment]
I think this would a be a good thing to put in the README. Purgecss does not work w/ Gatsby v1 so could just tell people that if they are using Gatsby v2 to use Purgecss instead.
