### ISSUE TITLE
CSS injected in wrong location

### ISSUE THREAD

**Issue by jrah** [rongierlach/gatsby-plugin-purify-css#9]
I am new to React and Gatsby so please excuse my ignorance. 

I am using [Gatsby Netllify plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms) with `gatsby-plugin-purify-css` when I include it in my `gatsby` config and let it run it seems to concat files from `cms.css` (from Netlify plugin I suspect) and/or `build-js-styles.css` (not sure if this is related to Netlify CMS) when I remove `gatsby-plugin-purify-css` it is not concatenated.

**Comment by jrah** [comment]
My issue seems to be related to #5, sorry about the duplicate issue.

**Comment by youfoundron** [comment]
No worries
